DoS\QueueBundle\Model\QueueMessage:
    type: mappedSuperclass
    table: dos_queue_message

    id:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO

    fields:
        name:
            type: string

        body:
            type: array

        receivedAt:
            type: datetime
            column: received_at
            nullable: true

        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create

        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
